// This file is generated by `twin-cli generate`. Do not edit manually.
// Re-generate with: twin-cli generate --spec specs/drive.toml

#![allow(unused_imports)]

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

// -----------------------------------------------------------------------
// API response types (Serialize)
// -----------------------------------------------------------------------

/// Google Drive v3 file resource representation.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3File {
    pub(crate) kind: String,
    pub(crate) id: String,
    pub(crate) name: String,
    pub(crate) mime_type: String,
    pub(crate) parents: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) size: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) web_view_link: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) app_properties: Option<BTreeMap<String, String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) permissions: Option<Vec<V3Permission>>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3Permission {
    pub(crate) id: String,
    #[serde(rename = "type")]
    pub(crate) permission_type: String,
    pub(crate) role: String,
    pub(crate) email_address: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3FileList {
    pub(crate) kind: String,
    pub(crate) files: Vec<V3File>,
}

// -----------------------------------------------------------------------
// HTTP body / query types (Deserialize)
// -----------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub(crate) struct CreateItemBody {
    pub(crate) actor_id: String,
    pub(crate) parent_id: String,
    pub(crate) name: String,
}

#[derive(Debug, Deserialize)]
pub(crate) struct ListChildrenQuery {
    pub(crate) actor_id: String,
}

#[derive(Debug, Deserialize)]
pub(crate) struct SetPermissionBody {
    pub(crate) actor_id: String,
    pub(crate) target_actor_id: String,
    pub(crate) role: String,
}

#[derive(Debug, Deserialize)]
pub(crate) struct MoveItemBody {
    pub(crate) actor_id: String,
    pub(crate) new_parent_id: String,
}

#[derive(Debug, Deserialize)]
pub(crate) struct ActorQuery {
    pub(crate) actor_id: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3CreateFileBody {
    pub(crate) name: String,
    pub(crate) mime_type: Option<String>,
    pub(crate) parents: Option<Vec<String>>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3UpdateFileBody {
    pub(crate) name: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3UpdateFileQuery {
    pub(crate) add_parents: Option<String>,
    /// Accepted but not acted on — the twin uses single-parent semantics, so setting `add_parents` implicitly replaces the existing parent.
    #[allow(dead_code)]
    pub(crate) remove_parents: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3ListFilesQuery {
    pub(crate) q: Option<String>,
    /// Accepted but not used — the twin always returns all fields.  Real Drive uses this for partial-response field masks.
    #[allow(dead_code)]
    pub(crate) fields: Option<String>,
    pub(crate) page_size: Option<usize>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3CreatePermissionBody {
    pub(crate) role: String,
    pub(crate) email_address: Option<String>,
    /// Twin extension: direct actor_id
    pub(crate) actor_id: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3GetFileQuery {
    pub(crate) alt: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V3UploadQuery {
    /// Upload type: `media` (simple) or `multipart` (multipart/related).
    #[allow(dead_code)]
    pub(crate) upload_type: Option<String>,
    pub(crate) name: Option<String>,
    pub(crate) mime_type: Option<String>,
    pub(crate) parents: Option<String>,
}
