// This file is generated by `twin-cli generate`. Do not edit manually.
// Re-generate with: twin-cli generate --spec specs/gmail.toml

#![allow(unused_imports)]

use serde::{Deserialize, Serialize};

// -----------------------------------------------------------------------
// API response types (Serialize)
// -----------------------------------------------------------------------

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1Message {
    pub(crate) id: String,
    pub(crate) thread_id: String,
    pub(crate) label_ids: Vec<String>,
    pub(crate) snippet: String,
    pub(crate) history_id: String,
    pub(crate) internal_date: String,
    pub(crate) size_estimate: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) payload: Option<V1Payload>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1Payload {
    pub(crate) mime_type: String,
    pub(crate) headers: Vec<V1Header>,
    pub(crate) body: V1Body,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub(crate) parts: Vec<V1Part>,
}

#[derive(Debug, Serialize)]
pub(crate) struct V1Header {
    pub(crate) name: String,
    pub(crate) value: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1Body {
    pub(crate) size: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) data: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) attachment_id: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1Part {
    pub(crate) part_id: String,
    pub(crate) mime_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) filename: Option<String>,
    pub(crate) headers: Vec<V1Header>,
    pub(crate) body: V1Body,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1MessageList {
    pub(crate) messages: Vec<V1MessageRef>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) next_page_token: Option<String>,
    pub(crate) result_size_estimate: u32,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1MessageRef {
    pub(crate) id: String,
    pub(crate) thread_id: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1Thread {
    pub(crate) id: String,
    pub(crate) history_id: String,
    pub(crate) snippet: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) messages: Option<Vec<V1Message>>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1ThreadList {
    pub(crate) threads: Vec<V1ThreadRef>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) next_page_token: Option<String>,
    pub(crate) result_size_estimate: u32,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1ThreadRef {
    pub(crate) id: String,
    pub(crate) snippet: String,
    pub(crate) history_id: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1Label {
    pub(crate) id: String,
    pub(crate) name: String,
    #[serde(rename = "type")]
    pub(crate) label_type: String,
    pub(crate) message_list_visibility: String,
    pub(crate) label_list_visibility: String,
    pub(crate) messages_total: u64,
    pub(crate) messages_unread: u64,
    pub(crate) threads_total: u64,
    pub(crate) threads_unread: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) color: Option<V1LabelColor>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1LabelColor {
    pub(crate) text_color: String,
    pub(crate) background_color: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1LabelList {
    pub(crate) labels: Vec<V1Label>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1Attachment {
    pub(crate) attachment_id: String,
    pub(crate) size: u64,
    /// Base64url-encoded data (matching Gmail API convention).
    pub(crate) data: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1Profile {
    pub(crate) email_address: String,
    pub(crate) messages_total: u64,
    pub(crate) threads_total: u64,
    pub(crate) history_id: String,
}

// -----------------------------------------------------------------------
// HTTP body / query types (Deserialize)
// -----------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub(crate) struct NativeSendBody {
    pub(crate) to: Vec<String>,
    pub(crate) subject: String,
    pub(crate) body: String,
    #[serde(default)]
    pub(crate) thread_id: Option<String>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct NativeModifyLabelsBody {
    #[serde(default)]
    pub(crate) add_label_ids: Vec<String>,
    #[serde(default)]
    pub(crate) remove_label_ids: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct NativeCreateLabelBody {
    pub(crate) name: String,
}

/// Query parameters for list messages/threads endpoints.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1ListQuery {
    /// Comma-separated label IDs.
    #[serde(default)]
    pub(crate) label_ids: Option<String>,
    #[serde(default = "default_v1_list_query_max_results")]
    pub(crate) max_results: u32,
    #[serde(default)]
    pub(crate) page_token: Option<String>,
    /// Gmail search query string (e.g. "in:sent after:2024/01/01 from:alice").
    #[serde(default)]
    pub(crate) q: Option<String>,
}

/// Query parameters for get message/thread endpoints.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1GetMessageQuery {
    #[serde(default = "default_v1_get_message_query_format")]
    pub(crate) format: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub(crate) struct V1SendBody {
    /// We accept simplified JSON instead of raw RFC 2822.
    pub(crate) raw: Option<String>,
    #[serde(default)]
    pub(crate) to: Vec<String>,
    #[serde(default)]
    pub(crate) cc: Vec<String>,
    #[serde(default)]
    pub(crate) bcc: Vec<String>,
    #[serde(default)]
    pub(crate) subject: Option<String>,
    #[serde(default)]
    pub(crate) body: Option<String>,
    #[serde(default)]
    pub(crate) thread_id: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1ModifyBody {
    #[serde(default)]
    pub(crate) add_label_ids: Vec<String>,
    #[serde(default)]
    pub(crate) remove_label_ids: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub(crate) struct V1CreateLabelBody {
    pub(crate) name: String,
    #[serde(default)]
    pub(crate) message_list_visibility: Option<String>,
    #[serde(default)]
    pub(crate) label_list_visibility: Option<String>,
    #[serde(default)]
    pub(crate) color: Option<V1LabelColorInput>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1UpdateLabelBody {
    #[serde(default)]
    pub(crate) name: Option<String>,
    #[serde(default)]
    pub(crate) message_list_visibility: Option<String>,
    #[serde(default)]
    pub(crate) label_list_visibility: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub(crate) struct V1LabelColorInput {
    pub(crate) text_color: String,
    pub(crate) background_color: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct V1InsertBody {
    /// Simplified insert (not raw RFC 2822).
    #[serde(default)]
    pub(crate) thread_id: Option<String>,
    #[serde(default)]
    pub(crate) label_ids: Vec<String>,
    pub(crate) from: String,
    pub(crate) to: Vec<String>,
    #[serde(default)]
    pub(crate) cc: Option<Vec<String>>,
    #[serde(default)]
    pub(crate) bcc: Option<Vec<String>>,
    pub(crate) subject: String,
    #[serde(default)]
    pub(crate) body: Option<String>,
    #[serde(default)]
    pub(crate) body_html: Option<String>,
    #[serde(default)]
    pub(crate) internal_date: Option<String>,
}

// -----------------------------------------------------------------------
// Default value functions for serde
// -----------------------------------------------------------------------

fn default_v1_list_query_max_results() -> u32 {
    100
}

fn default_v1_get_message_query_format() -> String {
    "full".to_string()
}
